version: '3.4'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  web:
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOSTNAME: db
      POSTGRES_PASSWORD: password
    command: ./littleredbroker/run.sh
    volumes:
      - ${PWD}:/opt/code
    ports:
      - "5000:5000"

volumes:
  pgdata: